### PR TITLE
Fix minor UI issues

### PR DESCRIPTION
**Pull request by jfrankl**
This pull request fixes all of the minor UI issues outlined in #690.

image

image

image
 
 Connects #690

### CODE REVIEW

**Comment by caseypt** [comment]
The app now has a horizontal scroll bar for me, and the plugin title scrolls with the page:

image

**Comment by caseypt** [comment]
The close button that appeared when you activated the map utils plugin has disappeared:

image


Previously (on `prototype`):

image

**Comment by caseypt** [comment]
Talked with @jfrankl re: the two above items.

Re: horizontal scroll bar, this is due to the new map print sandbox. It currently has crude styling for demonstration purposes. We'll be changing this soon, so no changes are needed here.

Re: map utils close button, we thought it was best to not have the "X" and to implement a more intuitive close workflow (clicking away or clicking the plugin again should close it). I'll open an issue.

**Comment by jfrankl** [comment]
Thanks @caseypt. Anything else I should do before I merge this?

**Comment by caseypt** [comment]
Nope. Looks good. +1.

**Comment by kdeloach** [comment]
Re: map utils... It might be easier just to eliminate the concept of map plugins, then we would have full control over this behavior. There are no other map plugins besides the ones in core, as far as I know.

**Pull request merged**
