### PR TITLE
Update JS

### PR DESCRIPTION
**Pull request by mmcfarland**
Updates Underscore, Backbone, ~jQuery, mCustomScrollbar

Connects #442

### CODE REVIEW

**Comment by caseypt** [comment]
Missed a passing of options [here](https://github.com/mmcfarland/GeositeFramework/blob/feature/update-js/src/GeositeFramework/js/SubRegion.js#L267).

**Comment by caseypt** [comment]
+1 besides the above error, which prevents subregions from activating. 

Verified that the core libraries have been updated and that the site is working.

```
Backbone.VERSION
"1.2.3"
_.VERSION
"1.8.3"
jQuery.fn.jquery
"1.9.0"
```

**Comment by mmcfarland** [comment]
Good catch, thanks.

**Comment by mmcfarland** [comment]
Updated with SubRegion options.

**Pull request merged**
