### PR TITLE
Make sure plugin click events are only bound once

### PR DESCRIPTION
**Pull request by lesserj**
## Overview

This PR resolves the issue in #1072.  Events are getting assigned more than once, and will trigger once for every assignment.  In the case of NCP, the print button will cause the print window to open three times and eventually cause the browser to crash in Chrome.

Connects #1072

### Demo

See #1072 for screenshot

### Notes

There are other ways to bind events that may be better, such as delegating the event to the events before the elements are even created and only calling the delegation once.  The implemented method is quick to implement without refactor and is performant.

## Testing Instructions

Click the print country summary button in NCP.  The print window should only appear once.

### CODE REVIEW

**Comment by kellyi** [comment]
Hi @lesserj! Thanks for fixing this bug!

I was able to recreate the bug described in #1072 and narrowed it down to something happening in the regional-planning plugin's custom print functionality. The changes here fix the bug while also still allowing that plugin & others to print as expected.

I did want to ask if you could retarget this pull request at `develop` rather than `master`? I tried to update the base branch through the GitHub UI, but doing so caused the retargeted PR to also include two unrelated merge commits from past releases along with the bugfix in 23f6fd1d2bc5f7fb87b0a4014f5e6741d6fc809b

It appears that the branch on which you originally did the work branched off `master`, so the process for adjusting that will involve

1. rebasing the `prusikmapping-master` branch onto `develop` so that it will include the print-related change but not the merge commits
2. force pushing `prusikmapping-master` to your fork's GitHub repository, which will then update the branch here with the branch containing only the print bugfix.
3. updating the target branch for this PR from `master` to `develop` via the GitHub user interface by clicking the "Edit" button and adjusting the target branch from the dropdown depicted here:

screen shot 2018-08-29 at 1 56 13 pm

If any of these steps are unclear, definitely let me know and I can help facilitate the process!

After the rebasing and retargeting I can approve this PR so it can be merged into `develop`.

I'll also take a look at the regional-planning plugin's code to see how it was causing the error in the first place so we can determine whether a change there might be warranted too.

**Comment by kellyi** [comment]
Hi @lesserj! I thought I'd comment again just in case this got missed in the shuffle of the holiday weekend.

Let me know if you'd like any help on rebasing this to prepare it for merging!

**Comment by lesserj** [comment]
@kellyi This had fallen off my radar.  I will go ahead and rebase later today.

**Comment by lesserj** [comment]
Closing in favor of https://github.com/CoastalResilienceNetwork/GeositeFramework/pull/1105 which is rebased off develop.

**Pull request closed without merging**
