### PR TITLE
Fix legend bugs

### PR DESCRIPTION
**Pull request by caseypt**
Fixes legend bugs reported in the demo. See commit messages for details.

**Testing instructions**
* Verify the behavior reported in each bug is fixed.

Connects to #507 
Connects to #508 
Connects to #509

### CODE REVIEW

**Comment by mmcfarland** [comment]
Sorry, this is getting more complicated, found two more edge cases:

* If you add la bunch of layers while the legend is minimized to the point where it will autoResize, when you maximize it the contents will extended outside of the legend body, presumably has to do with the 0 h/w of the body when minimized and doing calculations.
screenshot from 2016-01-21 10 32 53
* There's an issue when sometimes when the screen is relatively narrow (as in split screen), the legend can restore itself from minimized to an area under the plugin.  I kept thinking the legend was being removed, but it was just hidden underneath map layers.  If we could bump the z-index on the legend I think it'd fix this.

**Comment by mmcfarland** [comment]
Fixes provided work great.

**Comment by caseypt** [comment]
Pushed two fixes for the two bugs mentioned above.

**Comment by caseypt** [comment]
Updated with an attempted fix for browsers with big fonts/scrollbars.

**Comment by mmcfarland** [comment]
+1, all working nicely.

**Comment by caseypt** [comment]
Thanks for the thorough review.

**Pull request merged**
