### PR TITLE
Keep active plugin window open

### LINKED ISSUE #273: Save and Share state to include open plugin
When we add the Launchpad feature which can open specific plugins, utilize that code path to reopen the active plugin when a perma linke is activated.  The framework will need to capture that state.

### PR DESCRIPTION
**Pull request by mmcfarland**
When initializing a saved state, keep the appropriate plugin window
open.

Fixes #273

### CODE REVIEW

**Comment by mmcfarland** [comment]
@kdeloach Can you post steps to reproduce?  I can't get that to happen.

**Comment by kdeloach** [comment]
1. Goto http://hanoi-ubuntu-vm:84/
2. Click Map Layers > Coastal Resilience > Social and Economic > Families in Poverty
3. Click Save & Share
4. Navigate to permalink

Here's what I see at this point:
image

Trying to open other plugins at this point doesn't work.

**Comment by mmcfarland** [comment]
Seems to be an issue with the Layer Selector plugin when activating close to setting the state.  Looking into it now.  Other plugins don't seem to be affected.

**Comment by mmcfarland** [comment]
Updated.  @kdeloach Discovered #288 while fixing the issue you reported, but doesn't seem to be related to this PR.

**Comment by kdeloach** [comment]
Works great now +1

**Pull request merged**
