### PR TITLE
Style search input

### LINKED ISSUE #886: Deemphasize search control
Feedback from TNC:

>De-emphasize Search: smaller window on default, even as dark blue until user clicks inside find address.

### PR DESCRIPTION
**Pull request by jfrankl**
image

Fixes #886. CC @ajrobbins

### CODE REVIEW

**Comment by ajrobbins** [comment]
@jfrankl the search bar in this screenshot looks a little too eye-catching due to the light color, IMO. Can you make it less white and more blue, like you did with the green here?
pasted image at 2017_03_01 01_59 pm

**Comment by jfrankl** [comment]
@ajrobbins how does this look?

image

**Comment by ajrobbins** [comment]
I like it!

**Comment by caseycesari** [comment]
Looks good to me, though the original issues mentions that the control should become more visible once the user clicks inside it/it has focus.

**Comment by caseycesari** [comment]
Also, consider addressing https://github.com/CoastalResilienceNetwork/GeositeFramework/issues/905 while implementing this.

**Comment by ajrobbins** [comment]
Agreed re:
>the control should become more visible once the user clicks inside it/it has focus

**Comment by jfrankl** [comment]
@ajrobbins & @caseycesari what do you think of this direction? Casey said he'd be able to do the expand button by using [this code](https://jsbin.com/jukinehiru/edit?html,output). Then I'd make a few style modifications.

### Search Collapsed
search-collapsed

### Search Expanded
search-expanded

**Comment by caseycesari** [comment]
Looks good to me. Turning on the collapsed mode is a quick change for us. I'll wait to hear from @ajrobbins.

**Pull request merged**
