### PR TITLE
Keep plugin activate state for hibernating plugins and update plugin icons

### PR DESCRIPTION
**Pull request by caseypt**
### Overview

Updates the sidebar so that plugin icons remain highlighted when minimized, and also changes the filename for the sidebar plugin icon.

#### Demo

Observe the updated Regional Planning and Identify Point plugin icons (they are both active).

image

#### TODO

- [X] Keep active state for selected, but not visible (aka hibernating) plugins
- [x] Use updated plugin icons

Connects to #743

### CODE REVIEW

**Comment by kdeloach** [comment]
This is blocked until we receive updated icons.

**Comment by mmcfarland** [comment]
The needed icons are available here: https://github.com/CoastalResilienceNetwork/GeositeFramework/issues/729#issuecomment-263720994

**Comment by kdeloach** [comment]
@jfrankl Do we need to adjust the sidebar size to accomodate the new icons? There's some clipping.

image

**Comment by jfrankl** [comment]
We don't need to adjust the sidebar size, but we do need to apply some additional styling around the image to reduce the size. I can pair with you on this or you can create an issue for me to take on next sprint.

**Comment by kdeloach** [comment]
Cool. I'll create an issue to do a styling pass after the new icons get merged in.

**Pull request merged**
