### PR TITLE
Fixes #341

### LINKED ISSUE #341: Enhance the launchpad colors/design

### PR DESCRIPTION
**Pull request by ctaylo37**
Styled the Launchpad and made "tiny box" more responsive.

### CODE REVIEW

**Comment by caseypt** [comment]
@ctaylo37 Found a way to give the launchpad box an ID. I set the height to 80% as an example. Feel free to modify from here.

**Comment by ctaylo37** [comment]
Awesome!  This looks good to me.

**Comment by ctaylo37** [comment]
Can this be merged?

**Comment by caseypt** [comment]
Yes

**Pull request merged**
