### PR TITLE
Show infographic on start - revised

### PR DESCRIPTION
**Pull request by mapossum**

### CODE REVIEW

**Comment by mapossum** [comment]
This makes the change suggested in:

https://github.com/CoastalResilienceNetwork/GeositeFramework/pull/677

**Comment by caseypt** [comment]
+1

**Comment by kdeloach** [comment]
Nice change. 

Is this pull request supposed to be merged into `develop`, or `master`? It looks like it's targeting `master` right now, and bringing a few other commits (unrelated to this pull request) along for the ride.

I would suggest merging #677 and closing this pull request. Then we can open a new pull request to deploy all the changes from `develop` into `master`.

**Comment by mapossum** [comment]
Ok. Thanks.  Who does the actual merge of 677?

Gtr

**Comment by mmcfarland** [comment]
Superseded by #677

**Pull request closed without merging**
