### PR TITLE
Add support for zooming to layer extent

### PR DESCRIPTION
**Pull request by caseypt**
Supersedes #539. See #539 for details.

Connects to #520.

### CODE REVIEW

**Comment by caseypt** [comment]
Updated to work for all layer types.

**Comment by kdeloach** [comment]
The pull requests I merged created a conflict.

**Comment by caseypt** [comment]
Rebased.

**Comment by kdeloach** [comment]
Sorry, there's 1 more small change left.

**Comment by kdeloach** [comment]
Besides that, this works really well.

**Comment by kdeloach** [comment]
+1

**Pull request merged**
