### PR TITLE
Menu and sidebar improvements

### PR DESCRIPTION
**Pull request by caseypt**
#### Overview
* Add external link icon to items in the hamburger menu
*  Move tour link and update configuration

The styling of the help is coming from @jfrankl later.  Also the tour elements need to be updated to reflect the new layout, issue forthcoming.

Connects to #737

Testing:
screenshot from 2016-12-15 12 04 21
screenshot from 2016-12-15 12 03 34

### CODE REVIEW

**Comment by kdeloach** [comment]
I think this may be blocked until we receive design, according to https://github.com/CoastalResilienceNetwork/GeositeFramework/issues/737#issuecomment-261341167.

cc @jfrankl

**Comment by mmcfarland** [comment]
This is now waiting for https://github.com/CoastalResilienceNetwork/GeositeFramework/issues/783

**Comment by mmcfarland** [comment]
This is now ready to be worked on, as described in https://github.com/CoastalResilienceNetwork/GeositeFramework/issues/737#issuecomment-267362550

**Comment by mmcfarland** [comment]
This is updated and ready for a review now.

**Comment by kdeloach** [comment]
One thing I noticed is that the tour causes the horizontal scrollbar to appear.

image

**Comment by kdeloach** [comment]
We can fix this as part of #786.

**Pull request merged**
