### PR TITLE
Remove styleguide rules from main.css

### PR DESCRIPTION
**Pull request by caseypt**
These rules should only exist in one place. Encountered while working on #833.

**Testing**
- Verify that the rules removed here exist in `styleguide.css` and that the site generally looks the same.

Connects to #833

### CODE REVIEW

**Comment by kellyi** [comment]
Out of curiosity, could the first nine lines of `main.css` get removed, too? They're also in `styleguide.css`, but it may be that we need the `import` statement at least:

```
@import url("../fonts/fontello/css/mantle.css");
.clearfix:after,
.clearfix:before {
    content: " ";
    display: table
}
.clearfix:after {
    clear: both
}
```

**Comment by caseypt** [comment]
Good call. I'll take a look.

**Comment by kellyi** [comment]
Looks good otherwise! Double checked the `index` file to verify that the `styleguide.css` file was still being imported and it is.

**Comment by caseypt** [comment]
Made the change. Thanks.

**Pull request merged**
