### PR TITLE
Fix legend resizing

### PR DESCRIPTION
**Pull request by caseypt**
Various fixes to improve how the legend behaves and resizes. See commit message for details.

**Testing instructions**
- Add and remove map layers, turn on and off plugins, resize the legend, and report an edge cases. 
I'll try to fix any reported issues.

Also for consideration: https://github.com/CoastalResilienceNetwork/GeositeFramework/issues/559

Connects to #543

### CODE REVIEW

**Comment by kdeloach** [comment]
Adding a layer then removing it results in an empty map legend.

image

**Comment by caseypt** [comment]
> Adding a layer then removing it results in an empty map legend.

Thanks. Fixed.

**Comment by kdeloach** [comment]
+1

**Comment by mmcfarland** [comment]
+1, couldn't get an error out of it.

**Pull request merged**
