### PR TITLE
Plugin print and plugin print demo enhancements

### PR DESCRIPTION
**Pull request by caseycesari**
## Overview

To better demo the new plugin print workflow, the identify point plugin print workflow was polished up a bit. Some changes were made to the improve the workflow in general based on testing it with the identify point plugin.

See commit messages for details.

Connects #1007 

### Demo

tnc1

## Testing Instructions

- Open the identify point plugin and activate the plugin print feature.
- Toggle the checkboxes in the modal that appears.
- Verify that the printed document contains the images that corresponded to the checkboxes in the modal.
- Repeat this process in other browsers.

### CODE REVIEW

**Comment by kellyi** [comment]
Just saw this so going to set it up to test momentarily.

**Comment by caseycesari** [comment]
Thanks!

**Comment by kellyi** [comment]
Icons are showing up!

screen shot 2017-12-13 at 5 48 55 pm

**Comment by kellyi** [comment]
Here's Firefox:

screen shot 2017-12-13 at 5 52 21 pm

**Comment by caseycesari** [comment]
Thanks!

**Pull request merged**
