### PR TITLE
Activate subregion specified in saveCode

### LINKED ISSUE #315: Launchpad: Set subregions based on saved state
The launchpad scenarios may not respect the saved state for sub-regions.

### PR DESCRIPTION
**Pull request by mmcfarland**
For scenarios and saved states, pass along the active subregion if one is
specified to the framework and to the plugins.

There are some persistant issues with the layer_selector plugin relating
to #314

Fixes #315

### CODE REVIEW

**Comment by caseypt** [comment]
+1. Can't test at the moment, but the code looks good.

**Comment by mmcfarland** [comment]
Doesn't seem to be working with a permalink, even without layer_selector

**Comment by mmcfarland** [comment]
@caseypt I could only duplicate the issue you mentioned (failing on permalink version of save code) when the layer selector is in the project.  You said you could reproduce it on other plugins?

**Comment by caseypt** [comment]
Yeah I believe I removed both the layer selector and custom layer selector plug-in folders, reloaded the map, activated a subregion, then used the share code.

**Comment by caseypt** [comment]
I wasn't getting any errors. The map was zooming in, but the subregion was not becoming activated.

**Comment by mmcfarland** [comment]
Updated.  Attempts to further unify the saveState and scenario code to reduce duplication and discrepancies in behavior.  The new scenario saveCode for Flower/Risk should work similarly if activated from the LP or pasted into the hash URL, with the known issue of: #334.

**Comment by caseypt** [comment]
+1. I was able to launch a subregion from a permalink and the launchpad.

**Pull request merged**
