### PR TITLE
Disable laziness

### PR DESCRIPTION
**Pull request by kdeloach**
All map service data is preloaded the first time the layer selector is
opened.

Connects #555

### CODE REVIEW

**Comment by kdeloach** [comment]
Test by verifying that the loading indicator is displayed the first time you activate the layer selector. Layers that are loaded on-demand should be available by using the filter (ex. "Tidelands").

**Comment by kdeloach** [comment]
Rebased.

**Comment by mmcfarland** [comment]
Opening the layer selector initially gives me this output, looks like a service is not getting defined:
`ajax.js:25 ajaxUtil Error: Service 2012_Sandy/undefined/MapServer not found `

```
ajaxUtil Error: Service 2012_Sandy/undefined/MapServer not found 
    at Error (native)
    at Object.C.g.load (http://js.arcgis.com/o/232546/geosite-v1.0.8/dojo/dojo.js:432:426)
    at http://js.arcgis.com/o/232546/geosite-v1.0.8/dojo/dojo.js:241:426
    at g (http://js.arcgis.com/o/232546/geosite-v1.0.8/dojo/dojo.js:233:393)
    at l (http://js.arcgis.com/o/232546/geosite-v1.0.8/dojo/dojo.js:233:182)
    at resolve.callback (http://js.arcgis.com/o/232546/geosite-v1.0.8/dojo/dojo.js:235:10)
    at g (http://js.arcgis.com/o/232546/geosite-v1.0.8/dojo/dojo.js:234:96)
    at l (http://js.arcgis.com/o/232546/geosite-v1.0.8/dojo/dojo.js:233:182)
    at resolve.callback (http://js.arcgis.com/o/232546/geosite-v1.0.8/dojo/dojo.js:235:10)
    at http://js.arcgis.com/o/232546/geosite-v1.0.8/dojo/dojo.js:450:284
```

**Comment by kdeloach** [comment]
All comments have been addressed.

**Comment by mmcfarland** [comment]
+1

**Pull request merged**
