### PR TITLE
Merge static site branch into develop branch

### PR DESCRIPTION
**Pull request by caseycesari**
## Overview

Merges the static site branch into the `develop` branch.

## Testing instructions

- Checkout this branch, and verify the .NET site is gone and the static site is present.
- Try to build and run the site, and verify it works.

### CODE REVIEW

**Comment by fungjj92** [comment]
Quick note, the README can use an update :) It captures the state of conversion from ASP.NET.

**Comment by caseycesari** [comment]
README updated!

**Comment by fungjj92** [comment]
screen shot 2018-12-21 at 11 53 43 am

I'm checking the app on Chrome only, so far, and looking good on web mode. The navbar acts a little funny on mobile. Don't remember that, but also don't not remember that.

screen shot 2018-12-21 at 11 53 43 am

screen shot 2018-12-21 at 11 57 34 am

**Comment by caseycesari** [comment]
Good find. Looks like something got lost or added during the merge. I'll check it out.

**Comment by fungjj92** [comment]
No map on ie11 😮

**Comment by caseycesari** [comment]
Good catch! Just pushed a fix for IE.

**Comment by fungjj92** [comment]
IE and README look good ~ Also checked FF, and it behaves the same as I observed for Chrome. Once mobile fixed, this is good to go 👍

**Comment by caseycesari** [comment]
@fungjj92 Pushed a fix for the mobile issues. See commit message for details. Good catch! This is actually a bug that was in production.

**Comment by fungjj92** [comment]
Oh that's right. Those styling elements are for single plugin app mode. Just tested SPA. 

Nice work, and quick to the fixes! 👍

**Pull request merged**
