### PR TITLE
Add description popup to layer

### PR DESCRIPTION
**Pull request by kdeloach**
image

Connects #523

### CODE REVIEW

**Comment by kdeloach** [comment]
I mostly copied what already existed for "zoom to extent".

**Comment by caseypt** [comment]
Works well. Two things:

1) Like opacity, they can override the description from the config (there a bug that will prevent us from doing this. I'll open an issue).
2) This is probably outside the scope of the PR, but I think we should add some sort of "loading" indicator. For example, when zooming to an extent or getting the description for a layer that has been shown, there is a slight delay.

**Comment by caseypt** [comment]
Here's the issue I ran into when adding support for opacity: https://github.com/CoastalResilienceNetwork/GeositeFramework/issues/550

**Comment by caseypt** [comment]
+1

**Comment by kdeloach** [comment]
Fixed all bugs. I'll create an issue to add some kind of loading indicator.

**Comment by caseypt** [comment]
+1. Tested the changes.

**Pull request merged**
