### PR TITLE
Add support for combined layers

### PR DESCRIPTION
**Pull request by kdeloach**
Builds off #537

Preview:
image

Connects #481

### CODE REVIEW

**Comment by kdeloach** [comment]
Only the last 2 commits are relevant.

**Comment by caseypt** [comment]
:clap: Nice demo layer.

**Comment by mmcfarland** [comment]
+1, nice code.  Cool that you didn't need to touch the layer image fetching code to change the UI.  Also, agreed on clever demo layer name.

**Comment by kdeloach** [comment]
All updates made.

**Pull request merged**
