### PR TITLE
Styled Launchpad

### PR DESCRIPTION
**Pull request by ctaylo37**
-May still need some tweaks, but a good starting point.
-Broke the sub-regions.
-Needs JQuery scrollbars.
-Height of the export modal is cutting off the button.

### CODE REVIEW

**Comment by caseypt** [comment]
Looks good, but can you make the base header/content classses not `launchpad`? We are going to use that just for the launchpad modal.

**Comment by mmcfarland** [comment]
Agree with @caseypt about classname `launchpad`, but otherwise +1

**Comment by ctaylo37** [comment]
Yep.  Will Do.

**Comment by ctaylo37** [comment]
Make sure this looks good and I will merge.

**Comment by mmcfarland** [comment]
Looks good to me, +1

**Pull request merged**
