### PR TITLE
Single web update

### PR DESCRIPTION
**Pull request by cbessee**
Hey @cschneebeck,

I talked with Laura yesterday, and it sounds like you've volunteered to be the "gate-keeper" so to speak of the framework master branch. So, here's my first pull request :) Let me know if you'd rather pull this into development first and I can re-submit. 

Likewise, let me know if you have any questions about the code as you dig in. More than happy to hop on a quick screen share and talk through things if that would be helpful. 

Thanks!

- Cole

## Overview

This pull request contains updates to the framework to improve the mobile responsive aspects of the "single web app mode" as well as support for [Esri Feature Layers](https://developers.arcgis.com/javascript/3/jsapi/featurelayer.html) to enable user interaction with map features.

In general, we did our best to move away from using JS code for responsiveness and instead utilize JS to assign classes and provided updated html/css for a smoother, more performant mobile experience. 

### Updates

Development tasks for this set of updates were managed via a [Trello board](https://trello.com/b/zxmX4wHb/tnc-framework-tasks). 

The following is a list of improvements/feature updates included in this pull request:

- Update mobile layout of single web app mode. This includes moving away from separate tabs for app content and map and defaulting to a half map, half app content view with the ability for users to toggle between this view and a full map or full content view. [Link](https://trello.com/c/WN24uU3L/2-mobile-content-and-map-layout)
- Updating styling of the map legend in single web app mode. [Link](https://trello.com/c/pbLoQI7Z/1-map-legend)
- Change base font to Open Sans. [Link](https://trello.com/c/JGWubiyf/7-add-open-sans-web-font)
- Update save and share in single web app mode by removing the iFrame embed option and replacing with share to FB, twitter, and email. [Link](https://trello.com/c/2b8KbevJ/10-add-social-share-functionality-to-save-share-modal)
- Update map controls in the mobile view. [Link](https://trello.com/c/JnWK5vUV/6-handle-map-controls-zoom-basemap-selector-wrench-icon-at-mobile-breakpoint)
- Replace hamburger menu dropdown with a sliding off canvas menu. [Link](https://trello.com/c/LrSPGWH2/3-update-hamburger-menu-to-use-sliding-content-panel)
- Remove search for address in single web app mode. [Link](https://trello.com/c/8s609ReI/4-remove-top-bar-search-in-single-web-app-mode)
- Update styling of modal popups created with TinyBox. Provide helper classes that allow plugin developers to leverage these updated styles. [Link](https://trello.com/c/DdjlHoTC/5-add-ability-for-plugins-to-initiate-a-full-screen-modal-for-displaying-infographics-text-and-other-html-content)
- Add legend support for ESRI Feature Layers. [Link](https://trello.com/c/1KYgmJK2/12-add-support-for-esri-feature-layers-to-enable-user-interaction-with-features-on-the-map)

### Preview URL

A demo of the Natural Coastal Protection app running in SWA mode of this framework branch can be viewed [here](http://tnc-framework-dev.s3-website-us-west-2.amazonaws.com/)

### Testing

I've tested this framework branch in the following configurations:

- As a single web app build with the Natural Coastal Protection app
- As a single web app build with the NCP app and a story mode configured
- As a full framework build with NCP, Recreation and Tourism, and Regional Planning apps.

In general, I feel good about the level of testing around these updates but it would certainly be good to get a second set of eyes on things. Especially someone with more familiarity with other apps not developed by SpatialDev/Critigen in the past to make sure these updates don't have any unintended consequences for other apps.

### CODE REVIEW

**Comment by cschneebeck** [comment]
Hi Coal,

I think Laura was hoping that you work with me on this one. I did a quick test on some another app and think it would be a good idea to chat about this. Let me know your preferred meeting platform.

Cheers,
Casey Schneebeck
Web Developer | The Nature Conservancy - North America Region | 415-722-9768

**Comment by cbessee** [comment]
Hey @cschneebeck,

Ah - yes, of course. I should really double check who I am tagging before I hit send... 

I can set up a Zoom call for us to screen share/discuss. I'm out of the office tomorrow, but available anytime this Thursday or Friday. Can you shoot me an email with a time that will work well for you? cole.bessee@critigen.com

Thanks!

**Comment by cbessee** [comment]
Hey @cschneebeck,

I've added some commits to this branch and merged in master to incorporate the update to rebrandly for URL shortening. I had to hardcode the PROD build flag to true as I wasn't able to pass this variable to the server.py or run a build via terminal's localhost:8080 without main.py throwing an error. Laura mentioned you are out on vacation. Let me know when you are back and we can hopefully schedule another quick call to discuss the best way for me to handle this and any other integration points for my updates? Thanks!

**Comment by cschneebeck** [comment]
All looks good. I merged the changes into develop

**Pull request merged**
