### PR TITLE
Allow configurable size for scenario fa Icons

### LINKED ISSUE #367: Launchapd button icon config
Allow font awesome size in config for launchpad buttons.

### PR DESCRIPTION
**Pull request by mmcfarland**
A new key has been added to a Launchpad issue: faSize which affects the
size of the fa-icon in px units.

Fixes #367

### CODE REVIEW

**Comment by mmcfarland** [comment]
@ctaylo37 - Making the fa-icon size configurable ends up moving the labels around, can/should they be fixed to the bottom or just float like this?

**Comment by mmcfarland** [comment]
font-size

**Comment by ctaylo37** [comment]
What are the config options for the icon?  Color and size?  Seems like we may want to fix the label.

**Comment by mmcfarland** [comment]
Refs #380

**Comment by caseypt** [comment]
+1

**Pull request merged**
