### PR TITLE
"Pick a Geography" and subregion activation support

### PR DESCRIPTION
**Pull request by caseypt**
Subregions can be activated by either clicking on the
subregion shape on the map, or making a selection from the
launchpad "Pick a Geography" section.

Activating a subregion means 1) zooming to the extent of
the subregion (plus a little buffer), 2) turning off the
subregion graphics layers, and 3) triggering an event on
the map to let it know a subregion has been activated.

### CODE REVIEW

**Comment by caseypt** [comment]
Only bc2edd4 is part of this PR.

**Comment by mmcfarland** [comment]
+1

**Comment by mmcfarland** [comment]
Do you think we should hide the toggle subregion plugin when in an active subregion?  Turning it on shows the polygon and may interfere with clicking

**Comment by caseypt** [comment]
That's a good idea. Maybe we can just disable it, and apply some opacity to indicate that. I can do that in the card I'm working on now, which is the subregion header. I'm also going to handle deactivation.

**Pull request merged**
