### PR TITLE
Fix Ordering Issues

### PR DESCRIPTION
**Pull request by rajadain**
## Overview

Fixes tour, tooltip being obscured.

### Demo

image

## Testing Instructions

Ensure that map tools are above the legend, and that the help tour is not obscured by anything.

Connects #791 
Connects #797

### CODE REVIEW

**Comment by kellyi** [comment]
About to take a look at this.

**Comment by kellyi** [comment]
When the viewport's narrow enough that only the icons show in the launchpad, the help/tour bar renders properly above the sidebar div:

screen shot 2016-12-23 at 11 18 46 am

However, when the viewport's wider it seems like part of the help bar still sits behind the div:

screen shot 2016-12-23 at 11 19 33 am

**Comment by kellyi** [comment]
Tools popup now renders above the legend:

screen shot 2016-12-23 at 11 21 26 am

**Comment by rajadain** [comment]
Ah shoot, let me fix that real quick

**Comment by rajadain** [comment]
d9d1a2f should take care of it

**Comment by kellyi** [comment]
Cool. I'll pull that down now to test.

**Comment by kellyi** [comment]
New commit fixes the help menu on wider viewports:
screen shot 2016-12-23 at 11 38 12 am

Still works on narrow viewports, too:

screen shot 2016-12-23 at 11 39 06 am

**Comment by kellyi** [comment]
Looks good to me! +1

**Pull request merged**
